### ISSUE TITLE
Building on Linux needs -lbsd (comment, not really issue)

### ISSUE THREAD

**Issue by scruss** [yirkha/ntfsclone2vhd#1]
More of a comment than an issue: to build on Linux (Ubuntu 14.10, x86_64) you'll need to install libbsd, otherwise linking fails with:

```
ntfsclone2vhd.o: In function `main':
ntfsclone2vhd.c:(.text.startup+0x100): undefined reference to `setmode'
```

To install libbsd-dev:

```
sudo apt-get install libbsd-dev
```

To get the program to compile, edit Makefile and change the line:

```
    $(LD) -o $@ $<
```

to

```
    $(LD) -o $@ $< -lbsd
```

**Comment by yirkha** [comment]
Thanks for the feedback, Stewart.

Instead of modifying the Makefile and forcing extra dependencies, I have disabled the `setmode(stdin)` call altogether for non-Windows platforms, as the distinction between binary and text modes do not apply there anyway.
